# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-29 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='tomestamp',
            field=models.DateTimeField(auto_now_add=True, default=1511947294),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
