# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-29 09:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20171129_0921'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='tomestamp',
            new_name='created',
        ),
    ]
