# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-29 09:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20171129_0933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='created',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='updated',
        ),
    ]
